from __future__ import annotations

from typing import Any


def get_manifest() -> dict[str, Any]:
    return {
        "id": "clients",
        "name": "Clients",
        "version": "0.1.1",
        "description": "Client registry, profiles, and report workflows",
        "category": "operations",
        "enabled_by_default": True,
        "entry": {
            "router": "xem_module_clients.routes:create_router",
            "mount_prefix": "",
        },
        "dashboard": {
            "label": "Clients",
            "href": "/clients",
            "icon": "👥",
        },
        "compat": {
            "core_api": ">=1.0.0,<2.0.0",
        },
        "contract": {
            "required_deps": [
                "APP_NAME",
                "add_months",
                "attach_file_to_vector_store",
                "autoscore_ingest_self_check",
                "build_zentriq_docx",
                "cached_list_vector_stores",
                "client_autoscore_run_detail_handler",
                "client_create_from_kvk_handler",
                "client_create_page_handler",
                "client_crypto_ready",
                "client_default_kyc_level",
                "client_delete_handler",
                "client_detail_handler",
                "client_display_name",
                "client_edit_handler",
                "client_kvk_refresh_handler",
                "client_kyc_invite_create_handler",
                "client_note_verify_handler",
                "client_notes_page_handler",
                "client_payload_from_form",
                "client_quicknote_handler",
                "client_quicknote_push_handler",
                "client_quicknote_verify_handler",
                "client_report_page_handler",
                "client_report_submit_handler",
                "client_update_handler",
                "client_update_links_handler",
                "client_upload_files_handler",
                "client_vector_store_id",
                "clients_create_handler",
                "clients_lookup_handler",
                "clients_page_handler",
                "create_vector_store_file_batch",
                "emit_module_autoscore_input",
                "encrypt_client_payload",
                "ensure_id_expiry_from_raw",
                "ensure_sumsub_case",
                "execute",
                "execute_returning_id",
                "fetch_all",
                "fetch_one",
                "format_date_value",
                "format_zentriq_hr_report",
                "format_zentriq_quicknote",
                "format_zentriq_report",
                "format_zentriq_risk_report",
                "get_client",
                "get_setting",
                "has_permission",
                "httpx",
                "kvk_fetch_overview",
                "list_clients",
                "list_vector_store_files",
                "log_audit",
                "map_overview_to_client_fields",
                "normalize_vat_inputs",
                "note_preview",
                "openai_error",
                "parse_case_notes",
                "parse_date_value",
                "parse_note_timestamp",
                "quote",
                "read_case_notes",
                "relationship_risk_color",
                "require_any_permission",
                "require_permission",
                "require_user",
                "retrieve_vector_store_file",
                "risk_case_protocol",
                "send_template_email",
                "sumsub_config",
                "sumsub_levels",
                "sumsub_request",
                "templates",
                "timezone",
                "upload_file",
                "upsert_sumsub_applicant",
                "uuid",
                "vies_auth_headers",
                "vies_config",
                "zentriq_finance_fields",
                "zentriq_hr_fields",
                "zentriq_report_filename",
                "zentriq_risk_fields",
                "zentriq_select_options",
            ]
        },
        "permissions": {
            "required": ["client.view"],
            "admin": ["client.manage"],
        },
        "nav_items": [
            {"label": "Clients", "href": "/clients", "order": 25, "scope": "main"},
        ],
        "client_scope": {"enabled": False},
        "migrations": {"path": "migrations"},
        "health": {"path": "/clients/health"},
    }
